SportifyPod/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportifyPod.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SportifyPod/Controllers/MusicController.cs
using SpotifyAPI.Web;
using SpotifyAPI.Web.Auth;
using SpotifyAPI.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SportifyPod.Controllers
{
    public class MusicController : Controller
    {
        public string ClientId
        {
            get {
                string _clientId = string.Empty;
                if (ConfigurationManager.AppSettings["SpotifyClientId"] != null)
                    _clientId = ConfigurationManager.AppSettings["SpotifyClientId"].ToString();
                return _clientId;
            }   
        }

        public string SecretId
        {
            get {
                string _secretId = string.Empty;
                if (ConfigurationManager.AppSettings["SpotifySecretId"] != null)
                    _secretId = ConfigurationManager.AppSettings["SpotifySecretId"].ToString();
                return _secretId;
            }
        }

        public string SpotifyCallbackUrl
        {
            get {
                string _callbakUrl = string.Empty;
                if (ConfigurationManager.AppSettings["SpotifyCallbackUrl"] != null)
                    _callbakUrl = ConfigurationManager.AppSettings["SpotifyCallbackUrl"].ToString();
                return _callbakUrl;
            }
        }


        SpotifyWebAPI api = null;
        private SpotifyWebAPI ClientApi
        {
            get {
                string tokenType = "Bearer";

                string authUrl = GetAuthUri(ClientId, "token", SpotifyCallbackUrl, "34fFs29kd09", false);
                Token token = GetLocalToken();

                if (token == null || token.IsExpired())
                {
                    Response.Write("<script type='text/javascript'>window.open('" + authUrl + "', '_blank'');</script>");
                }
                if (api == null)
                api = new SpotifyWebAPI
                        {
                            AccessToken = token.AccessToken,
                                TokenType = tokenType
                        };

                return api;
            }
        }

        // GET: Music
        public async Task<ActionResult> Index()
        {                               

            string authUrl = GetAuthUri(ClientId, "token", SpotifyCallbackUrl, "34fFs29kd09", false);
            Token token = GetLocalToken();
            if (token == null || token.IsExpired())
            {
                Response.Redirect(authUrl);
                return View();
            }

            PrivateProfile userProfile = await ClientApi.GetPrivateProfileAsync();
            return View(userProfile);
        }

        [HttpGet]
        public async Task<ActionResult> MusicRecom()
        {
            PrepareNewReleaseAlbumList();

            PrepareTopArtistList();

            List<SimpleTrack> _list = new List<SimpleTrack>();
            var model = _list;
            return View(model);
        }

        private void PrepareNewReleaseAlbumList()
        {
            NewAlbumReleases data = ClientApi.GetNewAlbumReleases("SE");
            List<SelectListItem> _List = new List<SelectListItem>();
            SelectListItem item = null;
            foreach (var album in data.Albums.Items)
            {
                item = new SelectListItem();
                item.Text = album.Name;
                item.Value = album.Id;
                _List.Add(item);
            }
            _List.Insert(0, new SelectListItem() { Text = "Please select...", Value = "-1" });

            ViewData["NewRelease"] = _List;
        }

        private void PrepareTopArtistList()
        { 

            Paging<FullArtist> topArtist = ClientApi.GetUsersTopArtists();
            SelectListItem item = null;
            List<SelectListItem> _List = new List<SelectListItem>();
            foreach (var artist in topArtist.Items)
            {
                item = new SelectListItem();
                item.Text = artist.Name;
                item.Value = artist.Id;
                _List.Add(item);
            }

            ViewData["TopArtist"] = _List;
        }

        [HttpGet]
        [OutputCache(Duration = 0)]
        public async Task<ActionResult> GetRecommendationList(string trackSeedId, string artistSeedId)
        {
          
            List<string> artistSeed = new List<string>() { artistSeedId };
            List<string> trackSeed = new List<string>() { trackSeedId };  

            Recommendations recomList = await ClientApi.GetRecommendationsAsync(artistSeed, null, trackSeed, null, null, null);
            var model = recomList.Tracks;
            
            return PartialView("RecommendationList", model);

        }

        [HttpPost]
        public JsonResult GetTracks(string albumId)
        {          
            Paging<SimpleTrack> list = ClientApi.GetAlbumTracks(albumId);            
            return Json(list.Items);
        }

        public string GetArtistName(SimpleTrack track)
        {
            string result = string.Empty;
            foreach (var artist in track.Artists)
            {
                result += artist.Name + ", ";
            }
            return result;
        }



        public ActionResult CallBack()
        {

            Token token;
            string error = Request.QueryString["error"];
            if (error == null)
            {
                string accessToken = Request.QueryString["access_token"];
                string tokenType = Request.QueryString["token_type"];
                string expiresIn = Request.QueryString["expires_in"];
                if (tokenType != null)
                {

                    token = new Token
                    {
                        AccessToken = accessToken,
                        ExpiresIn = double.Parse(expiresIn),
                        TokenType = tokenType
                    };

                    SaveTokenFile(token);

                    Response.Redirect("~/Music/Index");

                }
            }
            else
            {
                token = new Token
                {
                    Error = error
                };
            }
            return View();
        }

        private void SaveTokenFile(Token token)
        {
            var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(token);
            System.IO.File.WriteAllText(Server.MapPath("/SportifyToken.json"), jsonString);
            System.Threading.Thread.Sleep(1000);
        }

        public string GetAuthUri(string clientId, string type, string redirectUri, string state, bool showDialog)
        {
            StringBuilder builder = new StringBuilder("https://accounts.spotify.com/authorize?");
            builder.Append("client_id=" + clientId);
            builder.Append($"&response_type={type}");
            builder.Append("&redirect_uri=" + HttpUtility.UrlEncode(redirectUri));
            builder.Append("&state=" + state);
            builder.Append("&scope=" + "user-read-private%20user-read-email%20user-library-read%20user-top-read");
            builder.Append("&show_dialog=" + showDialog.ToString());            
            return builder.ToString();
        }

        public Token GetLocalToken()
        {
            Token token = null;
            string tokenFile = Server.MapPath("/SportifyToken.json");
            string tokenContent = string.Empty;

            if (System.IO.File.Exists(tokenFile))
            {
                tokenContent = System.IO.File.ReadAllText(tokenFile);
                token = Newtonsoft.Json.JsonConvert.DeserializeObject<Token>(tokenContent);
            }

            return token;


        }
    }
}

SportifyPod/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SportifyPod/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SportifyPod/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SportifyPod/Views/Music/CallBack.cshtml
@{
    ViewBag.Title = "CallBack";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CallBack</h2>

<script type="text/javascript">
                window.onload = function() {
               if (document.URL.indexOf('#') > 0)
                window.location.href = document.URL.replace('#', '?');
             }
</script>

<div>
    You are connecting with Spotify now, a moment please ...
</div>

SportifyPod/Views/Music/Index.cshtml
@model SpotifyAPI.Web.Models.PrivateProfile

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome</h2>
@Html.LabelFor(p=>p.DisplayName)
@Html.DisplayFor(p=> p.DisplayName)
<br />
@Html.LabelFor(p=>p.Country)
@Html.DisplayFor(p=>p.Country)
<br />
@Html.LabelFor(p=>p.Email)
@Html.DisplayFor(p=>p.Email)

<br />
@Html.DisplayFor(p=>p.Id)
<br />
@Html.ActionLink("My Recommendation", "MusicRecom")

SportifyPod/Views/Music/MusicRecom.cshtml
@using SpotifyAPI.Web.Models
@model IEnumerable<SimpleTrack>
@{
    ViewBag.Title = "MusicRecom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MusicRecom</h2>

New Release Albums here:<br />

Album:  @Html.DropDownList("NewRelease", null, htmlAttributes: new { @id = "ddlNewRelease", @onchange = "UpdateTrackList()", @class = "form-control" })
@*@Html.DropDownList("Tracks", null, htmlAttributes: new { @id = "ddlTracks", @onchange = "updateContentList()", @class = "form-control" })*@
Tracks: <select class="form-control" id="ddlTracks"></select>

My Top Artists List:
@Html.DropDownList("TopArtist", null, htmlAttributes: new { @id = "ddlTopArtist", @onchange = "updateContentList()", @class = "form-control"})


@*@Html.DropDownList("Artist", null, htmlAttributes: new { @id = "ddlArtist", @onchange = "updateContentList()", @class = "form-control" })*@

<a class="btn btn-default glyphicon glyphicon-search" href="javascript:updateContentList();"></a>

<div id="dvCategoryResults" class="row">
    @{Html.RenderPartial("RecommendationList", Model);}
</div>

<script type="text/javascript">

    function updateContentList()
    {
        //var categoryId = $("#ddlNewRelease").val();
        //var artistId = $('#ddlArtist').val();
        var artistId = $('#ddlTopArtist').val();
        var trackId = $('#ddlTracks').val();
        $("#dvCategoryResults").load('@(Url.Action("GetRecommendationList", "Music",null, Request.Url.Scheme))?trackSeedId=' + trackId + '&artistSeedId=' + artistId);

    }

    function UpdateTrackList() {
        var _albumId = $('#ddlNewRelease').val();
        var url = "/Music/GetTracks";
        $.ajax({
            url: url,
            data: { albumId: _albumId },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Tracks</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Id + ">" + data[x].Name + "</option>";
                }
                $("#ddlTracks").html(markup).show();
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });
        
    }

    function GetTrackList() {
        //var procemessage = "<option value='0'> Please wait...</option>";
        //$("#ddlcity").html(procemessage).show();
        var _albumId = $('#ddlNewRelease').val();
        var url = "/Music/GetTracks";

        $.ajax({
            url: url,
            data: { albumId: _albumId },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Tracks</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                }
                $("#ddlTracks").html(markup).show();
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });

    }

</script>

SportifyPod/Views/Music/RecommendationList.cshtml
@using SpotifyAPI.Web.Models
@using SportifyPod.Controllers

@model List<SimpleTrack>

<br />
<div class="container">
    @foreach (SimpleTrack track in Model)
    {
        <div class="row">
            <div class="col-xs-6 col-md-7 text-left">
                <a href="@track.PreviewUrl">
                    <span class="glyphicon glyphicon-music " aria-hidden="true"></span>  @Html.DisplayFor(modelItem => track.Name)
                    </a>
</div>
            <div class="col-xs-6 col-md-3">@Html.DisplayFor(modelItem => track.ArtistsName)</div>
            <div class="col-xs-6 col-md-1">@Html.Raw(track.DurationText)</div>
        </div>
    }
    </div>

SportifyPod/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>